name: demo4-1
description: ''
version: 0.0.1
author: suraj.thakur@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: demo41
  parentArtefactID: surajthakurcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-06-12 10:09:52'
pipelines:
  pipelines/p1:
    name: p1
    description: ''
    author: suraj.thakur@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-06-12 10:09:52'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-06-12 10:09:52'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-06-12T10:09:52.439631Z'
  name: plibMaven
  version: 8.0.11
  id: '1096902734'
  createdAt: '2024-06-12T10:09:52.439631Z'
  type: plibMaven
- modifiedAt: '2024-06-12T10:09:52.439631Z'
  name: plibPypi
  version: 1.9.5
  id: '1960275984'
  createdAt: '2024-06-12T10:09:52.439631Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-06-12 10:09:12'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-06-12 10:09:12'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
