name: project_suraj_demo5
description: ''
version: 0.0.1
author: suraj.thakur@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: projectsurajdemo5
  parentArtefactID: surajthakurcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-06-10 07:20:45'
pipelines:
  pipelines/pipeline1:
    name: pipeline1
    description: ''
    author: suraj.thakur@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-06-10 07:20:45'
    datasets:
      inputs:
      - datasets/dataset1
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/dataset1:
    name: dataset1
    description: ''
    author: suraj.thakur@cloudaeon.net
    createdAt: '2024-06-10 07:27:57'
    mode: batch
    physicalDatasets:
      suraj_dev:
        fabricId: 10146
        datasetType: File
        description: ''
        author: suraj.thakur@cloudaeon.net
        createdAt: '2024-06-10 07:27:57'
templates: {}
jobs:
  jobs/job1:
    name: job1
    description: ''
    fabricUID: 10146
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: None
    timeout: null
    alerting:
      emails: suraj.thakur@cloudaeon.net
      onStart: true
      onSuccess: true
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-06-10 07:29:41'
    author: suraj.thakur@cloudaeon.net
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-06-10 07:20:45'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-06-10T07:20:45.667316Z'
  name: plibMaven
  version: 8.0.5
  id: '1732196219'
  createdAt: '2024-06-10T07:20:45.667316Z'
  type: plibMaven
- modifiedAt: '2024-06-10T07:20:45.667316Z'
  name: plibPypi
  version: 1.9.4
  id: '1942789120'
  createdAt: '2024-06-10T07:20:45.667316Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-06-10 07:20:28'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-06-10 07:20:28'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
